# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NI-JLC6dJ_atUUJVwGhZhkxWraz4xv_U

Programa de suma de 2 numeros
"""

#PASO 1: LECUTRA DE DATOS
n1 = int(input("Ingresa el primer numero: "))
n2 = int(input("Ingrese el segundo numero: "))
#PASO 2: PROCESO
suma = n1 + n2
#PASO 4: RESULTADO
print("La suma es ", suma)

"""Condiciones dobles"""

#PASO 1: LECTURA DE DATOS
edad = int(input("Ingrese su edad:"))
#PASO 2: PROCESO
if edad >= 18:
  mje = "Es mayor de edad"
else:
  mje = "Es menor de edad"
#PASO 3: RESULTADO
print (mje)

"""Practica de Laboratorio"""

#PASO 1: LECTURA DE DATOS
nota1 = float(input("Ingrese la primera nota: "))
nota2 = float(input("Ingrese la segunda nota: "))
nota3 = float(input("Ingrese la tercera nota: "))
#PASO 2: PROCESO
promedio = (nota1 + nota2 + nota3) / 3
if promedio >= 11:
  alu = "Esta aprobado"
else:
  alu = "Esta desaprobado"
#PASO 3: RESULTADO
print(alu)